# H2

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
# Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pay
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update

kafka.clusters.bootstrapservers: localhost:29092
logging.topic: wane.logging.out.stdout
service.membership.url: http://membership-service:8080 #컨테이너 외부의 포트가 아니라 내부의 포트로 작성해야함
task.topic: wane.task.topic
task.result.topic: wane.task.result.topic