version: '1'
services:
  axon-server:
    container_name: axon-server
    image: axoniq/axonserver
    networks:
      - pay_network
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events
      - axonserver-log:/axonserver/log
      - axonserver-config:/axonserver/config:ro



  mysql:
    image: mysql:8.0
    networks:
      - pay_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  membership-service:
    image: study-msa-with-project-membership-service:1.0.1
    networks:
      - pay_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=wane.logging.out.stdout
  banking-service:
    image: study-msa-with-project-banking-service:1.0.0
    networks:
      - pay_network
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server:8124
      - AXON_SERIALIZER_EVENTS=jackson
      - AXON_SERIALIZER_MESSAGES=jackson
      - AXON_SERIALIZER_GENERAL=xstream
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=wane.logging.out.stdout
      - SERVICE_MEMBERSHIP_URL=http://membership-service:8080 #컨테이너 외부의 포트가 아니라 내부의 포트로 작성해야함
  money-service:
    image: study-msa-with-project-money-service:1.0.0
    networks:
      - pay_network
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server:8124
      - AXON_SERIALIZER_EVENTS=jackson
      - AXON_SERIALIZER_MESSAGES=jackson
      - AXON_SERIALIZER_GENERAL=xstream
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=wane.logging.out.stdout
      - SERVICE_MEMBERSHIP_URL=http://membership-service:8080 #컨테이너 외부의 포트가 아니라 내부의 포트로 작성해야함
      - TASK_TOPIC=wane.task.topic
      - TASK_RESULT_TOPIC=wane.task.result.topic

  logging-consumer:
    image: study-msa-with-project-logging-consumer:1.0.0
    networks:
      - pay_network
    ports:
      - "9998:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=wane.logging.out.stdout

  task-consumer:
    image: study-msa-with-project-task-consumer:1.0.0
    networks:
      - pay_network
    ports:
      - "9999:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=wane.logging.out.stdout
      - TASK_TOPIC=wane.task.topic
      - TASK_RESULT_TOPIC=wane.task.result.topic

  remittance-service:
    image: study-msa-with-project-remittance-service:1.0.0
    networks:
      - pay_network
    ports:
      - "8084:8080"
    restart: always
    depends_on:
      - kafka
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=wane.logging.out.stdout
      - TASK_TOPIC=wane.task.topic
      - TASK_RESULT_TOPIC=wane.task.result.topic
      - SERVICE_MEMBERSHIP_URL=http://membership-service:8080 #컨테이너 외부의 포트가 아니라 내부의 포트로 작성해야함
      - SERVICE_BANKING_URL=http://banking-service:8080 #컨테이너 외부의 포트가 아니라 내부의 포트로 작성해야함
      - SERVICE_MONEY_URL=http://money-service:8080 #컨테이너 외부의 포트가 아니라 내부의 포트로 작성해야함


  zookeeper:
    image: 'arm64v8/zookeeper:3.8'
    networks:
      - pay_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none



  kafka:
    image: 'bitnami/kafka:3.4.1'
    networks:
      - pay_network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=LC://kafka:29092,LX://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LC
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - pay_network
    ports:
      - "8989:8080"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

volumes:
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon-server-se/data
      o: bind
  axonserver-events:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon-server-se/events
      o: bind
  axonserver-log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon-server-se/log
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon-server-se/config
      o: bind

networks:
  pay_network:
    driver: bridge