# H2

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
# Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pay
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update


service:
  money:
    url: http://money-service:8080
  membership:
    url: http://membership-service:8080